---
Organizations:    
        - &OrdererOrg
                Name: OrdererOrg
                ID: OrdererMSP
                MSPDir: /var/anzjointlab/ca-files/ordererOrganizations/msp

                Policies:
                        Readers:
                                Type: Signature
                                Rule: "OR('OrdererMSP.member')"
                        Writers:
                                Type: Signature
                                Rule: "OR('OrdererMSP.member')"
                        Admins:
                                Type: Signature
                                Rule: "OR('OrdererMSP.admin')"

        - &org1
                Name: Org1MSP
                ID: Org1MSP
                MSPDir: /var/anzjointlab/ca-files/peerOrganizations/org1.anzjointlab.com/msp
                
                Policies:
                        Readers:
                                Type: Signature
                                Rule: "OR('Org1MSP.admin', 'Org1MSP.peer', 'Org1MSP.client')"
                        Writers:
                                Type: Signature
                                Rule: "OR('Org1MSP.admin', 'Org1MSP.client')"
                        Admins:
                                Type: Signature
                                Rule: "OR('Org1MSP.admin')"

                AnchorPeers:
                        - Host: peer0.org1.anzjointlab.com
                          Port: 7055
        - &org2
                Name: Org2MSP
                ID: Org2MSP
                MSPDir: /var/anzjointlab/ca-files/peerOrganizations/org2.anzjointlab.com/msp


                Policies:
                        Readers:
                                Type: Signature
                                Rule: "OR('Org2MSP.admin', 'Org2MSP.peer', 'Org2MSP.client')"
                        Writers:
                                Type: Signature
                                Rule: "OR('Org2MSP.admin', 'Org2MSP.client')"
                        Admins:
                                Type: Signature
                                Rule: "OR('Org2MSP.admin')"                

                
                AnchorPeers:
                        - Host: peer0.org2.anzjointlab.com
                          Port: 7056
        - &org3
                Name: Org3MSP
                ID: Org3MSP
                MSPDir: /var/anzjointlab/ca-files/peerOrganizations/org3.anzjointlab.com/msp



                Policies:
                        Readers:
                                Type: Signature
                                Rule: "OR('Org3MSP.admin', 'Org3MSP.peer', 'Org3MSP.client')"
                        Writers:
                                Type: Signature
                                Rule: "OR('Org3MSP.admin', 'Org3MSP.client')"
                        Admins:
                                Type: Signature
                                Rule: "OR('Org3MSP.admin')"


                AnchorPeers:
                        - Host: peer0.org3.anzjointlab.com
                          Port: 7057



Capabilities:

        Global: &ChannelCapabilities
                V1_1: true

        Orderer: &OrdererCapabilities
                V1_1: true

        Application: &ApplicationCapabilities
                V1_2: true


Application: &ApplicationDefaults
        Organizations:

        Policies:
                Readers:
                        Type: ImplicitMeta
                        Rule: "ANY Readers"
                Writers:
                        Type: ImplicitMeta
                        Rule: "ANY Writers"
                Admins:
                        Type: ImplicitMeta
                        Rule: "MAJORITY Admins"

        Capabilities:
                <<: *ApplicationCapabilities


Orderer: &OrdererDefaults
        OrdererType: solo
        Addresses:
           - orderer.anzjointlab.com:8055
        BatchSize:
                MaxMessageCount: 10
                AbsoluteMaxBytes: 99 MB
                PreferredMaxBytes: 512 KB



        Kafka:
                Brokers:
                        - kafka0:9092
                        - kafka1:9092
                        - kafka2:9092
                        - kafka3:9092
        Organizations:
        Policies:
                Readers:
                        Type: ImplicitMeta
                        Rule: "ANY Readers"
                Writers:
                        Type: ImplicitMeta
                        Rule: "ANY Writers"
                Admins:
                        Type: ImplicitMeta
                        Rule: "MAJORITY Admins"
                BlockValidation:
                        Type: ImplicitMeta
                        Rule: "ANY Writers"

        Capabilities:
                <<: *OrdererCapabilities


Channel: &ChannelDefaults
        Policies:
                Readers:
                        Type: ImplicitMeta
                        Rule: "ANY Readers"
                Writers:
                        Type: ImplicitMeta
                        Rule: "ANY Writers"
                Admins:
                        Type: ImplicitMeta
                        Rule: "MAJORITY Admins"

        Capabilities:
                <<: *ChannelCapabilities




Profiles:
        ThreeOrgsOrdererGenesis:
                Orderer:
                        <<: *OrdererDefaults
                        Organizations:
                                - *OrdererOrg
                Consortiums:
                        SampleConsortium:
                                Organizations:
                                        - *org1
                                        - *org2
                                        - *org3
        ThreeOrgsChannel:
                Consortium: SampleConsortium
                Application:
                        <<: *ApplicationDefaults
                        Organizations:
                                - *org1
                                - *org2
                                - *org3


