---
Organizations:    
        - &OrdererOrg
                Name: OrdererOrg
                ID: OrdererMSP
                MSPDir: /var/anzjointlab/crypto-config/ordererOrganizations/msp
        - &org1
                Name: Org1MSP
                ID: Org1MSP
                MSPDir: /var/anzjointlab/crypto-config/peerOrganizations/org1.anzjointlab.com/msp
                
                AnchorPeers:
                        - Host: peer0.org1.anzjointlab.com
                          Port: 7051
        - &org2
                Name: Org2MSP
                ID: Org2MSP
                MSPDir: /var/anzjointlab/crypto-config/peerOrganizations/org2.anzjointlab.com/msp

                AnchorPeers:
                        - Host: peer0.org2.anzjointlab.com
                          Port: 7051
        - &org3
                Name: Org3MSP
                ID: Org3MSP
                MSPDir: /var/anzjointlab/crypto-config/peerOrganizations/org3.anzjointlab.com/msp

                AnchorPeers:
                        - Host: peer0.org3.anzjointlab.com
                          Port: 7051



Application: &ApplicationDefaults
        Organizations:

Orderer: &OrdererDefaults
        OrdererType: solo
        Addresses:
           - orderer.anzjointlab.com:7050
        BatchSize:
                MaxMessageCount: 10
                AbsoluteMaxBytes: 99 MB
                PreferredMaxBytes: 512 KB
        Kafka:
                Brokers:
                        - 127.0.0:9092
        Organizations:


Profiles:
        ThreeOrgsOrdererGenesis:
                Orderer:
                        <<: *OrdererDefaults
                        Organizations:
                                - *OrdererOrg
                Consortiums:
                        SampleConsortium:
                                Organizations:
                                        - *org1
                                        - *org2
                                        - *org3
        ThreeOrgsChannel:
                Consortium: SampleConsortium
                Application:
                        <<: *ApplicationDefaults
                        Organizations:
                                - *org1
                                - *org2
                                - *org3


