OrdererOrgs:
        - Name: Orderer
          Doamain: anzjointlab.com
          Specs:
                  - Hostname: orderer
                    CommonName: orderer.anzjointlab.com
          CA: 
                OrganizationUnit: admin
PeerOrgs:
        - Name: bc_org1
          Domain: org1.anzjointlab.com
          Template:
                  Count: 3
                  Users:
                          Count: 4
        - Name: bc_org2
          Domain: org2.anzjointlab.com
          Template:
                  Count: 3
                  Users:
                          Count: 4
        - Name: bc_org3
          Domain: org3.anzjointlab.com
          Template:
                  Count: 3
                  Users:
                          Count: 4

