# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
# ssn - solo-single-net SOLO单机网络
#

version: '2'

volumes:
  orderer.anzjointlab.com:
  peer0.org1.anzjointlab.com:
  peer1.org1.anzjointlab.com:
  peer2.org1.anzjointlab.com:
  peer0.org2.anzjointlab.com:
  peer1.org2.anzjointlab.com:
  peer2.org2.anzjointlab.com:

  peer0.org3.anzjointlab.com:
  peer1.org3.anzjointlab.com:
  peer2.org3.anzjointlab.com:

networks:
  ssn:

services:

  orderer.anzjointlab.com:
    container_name: orderer.anzjointlab.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ./crypto-config/ordererOrganizations/anzjointlab.com/orderers/orderer.anzjointlab.com/msp:/var/hyperledger/orderer/msp
    - ./crypto-config/ordererOrganizations/anzjointlab.com/orderers/orderer.anzjointlab.com/tls/:/var/hyperledger/orderer/tls
    - orderer.anzjointlab.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
    networks:
      - ssn

  peer0.org1.anzjointlab.com:
    container_name: peer0.org1.anzjointlab.com
   image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_byfn
      - CORE_LOGGING_LEVEL=INFO
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.org1.anzjointlab.com
      - CORE_PEER_ADDRESS=peer0.org1.anzjointlab.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.anzjointlab.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.anzjointlab.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org1.anzjointlab.com/peers/peer0.org1.anzjointlab.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/org1.anzjointlab.com/peers/peer0.org1.anzjointlab.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org1.anzjointlab.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053
    networks:
      - ssn

  peer1.org1.anzjointlab.com:
    container_name: peer1.org1.anzjointlab.com
   image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_byfn
      - CORE_LOGGING_LEVEL=INFO
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer1.org1.anzjointlab.com
      - CORE_PEER_ADDRESS=peer1.org1.anzjointlab.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.anzjointlab.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.anzjointlab.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org1.anzjointlab.com/peers/peer1.org1.anzjointlab.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/org1.anzjointlab.com/peers/peer1.org1.anzjointlab.com/tls:/etc/hyperledger/fabric/tls
        - peer1.org1.anzjointlab.com:/var/hyperledger/production

    ports:
      - 8051:7051
      - 8053:7053
    networks:
      - ssn

  peer0.org2.anzjointlab.com:
    container_name: peer0.org2.anzjointlab.com
   image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_byfn
      - CORE_LOGGING_LEVEL=INFO
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.org2.anzjointlab.com
      - CORE_PEER_ADDRESS=peer0.org2.anzjointlab.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.anzjointlab.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org2.anzjointlab.com:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org2.anzjointlab.com/peers/peer0.org2.anzjointlab.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/org2.anzjointlab.com/peers/peer0.org2.anzjointlab.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org2.anzjointlab.com:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053
    networks:
      - ssn

  peer1.org2.anzjointlab.com:
    container_name: peer1.org2.anzjointlab.com
   image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_byfn
      - CORE_LOGGING_LEVEL=INFO
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer1.org2.anzjointlab.com
      - CORE_PEER_ADDRESS=peer1.org2.anzjointlab.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.anzjointlab.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.anzjointlab.com:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org2.anzjointlab.com/peers/peer1.org2.anzjointlab.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/org2.anzjointlab.com/peers/peer1.org2.anzjointlab.com/tls:/etc/hyperledger/fabric/tls
        - peer1.org2.anzjointlab.com:/var/hyperledger/production
    ports:
      - 10051:7051
      - 10053:7053
    networks:
      - ssn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.anzjointlab.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.anzjointlab.com/peers/peer0.org1.anzjointlab.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.anzjointlab.com/peers/peer0.org1.anzjointlab.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.anzjointlab.com/peers/peer0.org1.anzjointlab.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.anzjointlab.com/users/Admin@org1.anzjointlab.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.anzjointlab.com
      - peer0.org1.anzjointlab.com
      - peer1.org1.anzjointlab.com
      - peer0.org2.anzjointlab.com
      - peer1.org2.anzjointlab.com
    networks:
      - ssn
